%YAML:1.0

# 0 kf 1 ba
fusion_model: 0

# predict type
use_imu: 0
wheel_use_type: 1

# obs type
use_gps: 1
use_camera: 1

# sensor conv
gyro_noise: 1e-02
gyro_bias_noise: 1e-03
acc_noise: 1e-01
acc_bias_noise: 1e-02

gps_x_noise: 0.5
gps_y_noise: 0.5
gps_z_noise: 0.5

# wheel
# new
wheel_kl: 0.00047820240382508
wheel_kr: 0.00047768621928995
wheel_b: 1.52439
wheel_noise_factor: 0.2
# old
encoder_resolution: 0.00047820240382508
wheel_x_noise: 0.1
wheel_y_noise: 0.1
wheel_z_noise: 0.1
fix_yz_in_eskf: 0

# data
play_speed: 1.0
data_path: /home/l/slam/data
#data_path: /home/fengbro/book_ws/Modular_Multi-sensor_Fusion/data